//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dershane_sistem.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mustafaEntities2 : DbContext
    {
        public mustafaEntities2()
            : base("name=mustafaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Alanlar> Alanlar { get; set; }
        public virtual DbSet<Borclarr> Borclarr { get; set; }
        public virtual DbSet<Giderler> Giderler { get; set; }
        public virtual DbSet<Ogrenci> Ogrenci { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Siniflar> Siniflar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Kasa> Kasa { get; set; }
        public virtual DbSet<RehberOgretmen> RehberOgretmen { get; set; }
    
        public virtual int mustafa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mustafa");
        }
    
        public virtual ObjectResult<musti_Result> musti(string alan)
        {
            var alanParameter = alan != null ?
                new ObjectParameter("alan", alan) :
                new ObjectParameter("alan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<musti_Result>("musti", alanParameter);
        }
    }
}
